#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Wait for postgres if using it
if [ -n "${PG_HOST:-}" ]; then
    echo "Waiting for postgres..."
    while ! nc -z "${PG_HOST}" "${PG_PORT:-5432}"; do
      sleep 0.1
    done
    echo "PostgreSQL started"
fi

echo "Running migrations..."
python manage.py migrate --no-input

echo "Collecting static files..."
python manage.py collectstatic --no-input --clear
# python manage.py seed_products --force

echo "Starting server..."
exec python manage.py runserver 0.0.0.0:8000